export const CLIENT_ACTION = {
    WS_OPEN: "CLIENT_ACTION.WS_OPEN",

    CONNECT: "CLIENT_ACTION.CONNECT",
    DISCONNECT: "CLIENT_ACTION.DISCONNECT",

    NEW_GAME: "CLIENT_ACTION.NEW_GAME",

    JOIN_GAME: "CLIENT_ACTION.JOIN_GAME",
    LEAVE_GAME: "CLIENT_ACTION.LEAVE_GAME",

    START_GAME: "CLIENT_ACTION.START_GAME",

    ATTACK_POS: "CLIENT_ACTION.ATTACK_POS",
    SUBMIT_PREP: "CLIENT_ACTION.SUBMIT_PREP",
};

export const SERVER_ACTION = {
    SEND_CLIENT_TOKEN: "SERVER_ACTION.SEND_CLIENT_TOKEN",
    CLOSE_SESSION: "SERVER_ACTION.CLOSE_SESSION",
};

export const SESSION_ACTION = {
    GET_SQUARES: "SESSION_ACTION.GET_SQUARES",
    GET_GRID: "SESSION_ACTION.GET_GRID",

    POST_SQUARES: "SESSION_ACTION.POST_SQUARES",
    POST_GRID: "SESSION_ACTION.POST_GRID",
    POST_PROXY_GRID: "SESSION_ACTION.POST_PROXY_GRID",

    START_PREP: "SESSION_ACTION.START_PREP",
    END_PREP: "SESSION_ACTION.END_PREP",
    START_TURN: "SESSION_ACTION.START_TURN",
    END_TURN: "SESSION_ACTION.END_TURN",

    END_GAME: "SESSION_ACTION.END_GAME",
};

export const RESPONSE = {
    SUCCESS: "RESPONSE.SUCCESS",
    ERROR: "RESPONSE.ERROR",
};

export const ALL_ENUMS = {
    ...SESSION_ACTION,
    ...CLIENT_ACTION,
    ...SERVER_ACTION,
    ...RESPONSE,
};

Object.freeze(CLIENT_ACTION);
Object.freeze(SESSION_ACTION);
Object.freeze(SERVER_ACTION);
Object.freeze(RESPONSE);

Object.freeze(ALL_ENUMS);
